repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.19.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
