"""
Xplore DS :: Cookbook Script Template

Standard pipeline template for scripts under ``cookbook/``.

Author: daniel.dominguet@gmail.com
"""

import sys
from pathlib import Path

from dotenv import load_dotenv

from xploreds.log.xds_log import XploreDSLogging

PROJECT_MARKER = "pyproject.toml"


def resolve_project_root(start: Path | None = None) -> Path:
    """
    Locate the XploreDS project root by searching for ``pyproject.toml``.

    Args:
        start: Directory to begin the search. Defaults to this file's folder.

    Returns:
        Absolute path to the project root.

    Raises:
        RuntimeError: When ``pyproject.toml`` cannot be found in any parent folder.
    """
    current = (start or Path(__file__).resolve().parent)

    for path in (current, *current.parents):
        if (path / PROJECT_MARKER).is_file():
            return path

    raise RuntimeError(
        f"Could not find {PROJECT_MARKER} starting from {current}. "
        "Run the script from within the XploreDS repository."
    )


def create_logger(project_root: Path, script_path: Path) -> XploreDSLogging:
    """
    Create the run logger for the current script.

    Args:
        project_root: Root directory of the XploreDS project.
        script_path: Path to the script file being executed.

    Returns:
        Configured ``XploreDSLogging`` instance.
    """
    return XploreDSLogging(
        project_root=str(project_root),
        script_name=script_path.name,
    )


def configure_script(log: XploreDSLogging) -> None:
    """
    Configure script parameters and runtime options.

    Args:
        log: Active logger for the current run.
    """
    log.title("Script setup")
    # TODO: load configs, set seeds, define paths


def load_datasets(log: XploreDSLogging) -> None:
    """
    Load input datasets for the pipeline.

    Args:
        log: Active logger for the current run.
    """
    log.title("Loading datasets")
    # TODO: read files from data/ or external sources


def apply_preprocessing(log: XploreDSLogging) -> None:
    """
    Apply preprocessing and feature engineering steps.

    Args:
        log: Active logger for the current run.
    """
    log.title("Applying preprocessing steps")
    # TODO: clean, encode, scale, split


def apply_business_rules(log: XploreDSLogging) -> None:
    """
    Apply domain-specific business rules.

    Args:
        log: Active logger for the current run.
    """
    log.title("Applying business rules")
    # TODO: filters, validations, domain constraints


def save_output_artifacts(log: XploreDSLogging) -> None:
    """
    Persist outputs, models, and reports generated by the run.

    Args:
        log: Active logger for the current run.
    """
    log.title("Saving output artifacts")
    # TODO: save to runs/ artifacts folder or data/output


def main() -> None:
    """Execute the cookbook script pipeline."""
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(line_buffering=True)

    script_path = Path(__file__).resolve()
    project_root = resolve_project_root(script_path.parent)

    load_dotenv(project_root / ".env")

    log = create_logger(project_root, script_path)
    log.init_run()
    log.log_environment_setup()

    try:
        configure_script(log)
        load_datasets(log)
        apply_preprocessing(log)
        apply_business_rules(log)
        save_output_artifacts(log)
    finally:
        log.close_run()


if __name__ == "__main__":
    main()
